### ISSUE TITLE
Support for Mac Catalyst 

### ISSUE THREAD

**Issue by AmeddahAchraf** [ionic-team/capacitor-swift-pm#11]
### Problem
Mac Catalyst support
After navigating inside the Capacitor and Cordova projects, I noticed they already support Mac Catalyst SDK
Is it possible to also archive for these destinations alongside iOS?

```
build_capacitor_macOS() {
  xcodebuild archive \
    -scheme Capacitor \
    -workspace Capacitor.xcworkspace \
    -destination "generic/platform=macOS,variant=Mac Catalyst" \
    -archivePath ./Build/macOS \
    SKIP_INSTALL=NO \
    SWIFT_SERIALIZE_DEBUGGING_OPTIONS=NO \
    DEBUG_INFORMATION_FORMAT="dwarf-with-dsym" \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES
}
```

**Comment by Steven0351** [comment]
Capacitor actually does not officially support Mac Catalyst as a target, many of our plugins are incompatible and it is not a target validated as part of testing for releases, bug fixes, or regressions. Since the core capacitor team doesn't support Catalyst as a target, I can't justify adding it to the xcframework build hosted and distributed here.
